/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import entities.Tracker;
import entities.Vehicule;
import entities.VehiculeTracker;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.VehiculeTrackerService;
import service.TrackerService;
import service.VehiculeServices;

/**
 *
 * @author BISSAOUI YASSINE
 */
public class AffecterTrackerVehicule extends javax.swing.JInternalFrame {

    private TrackerService ts ;
    private VehiculeServices vs ;
    private DefaultTableModel model;
    private VehiculeTrackerService vts;
    private static int id ;

    /**
     * Creates new form AffecterTrackerVehicule
     */
    public AffecterTrackerVehicule() {
        initComponents();
        ts = new TrackerService();
        vs = new VehiculeServices();
        vts =  new VehiculeTrackerService();
        model = (DefaultTableModel) listeVehiculeTracker.getModel();
        loadTrackers();
        loadVehicule();
        loadVehiculeTracker();
        Groupe.add(RadioAffecter);
        Groupe.add(RadioDesaffecter);
        RadioAffecter.setSelected(true);
        DateFin.setEnabled(false);
                
    }

     private void loadTrackers() {
         ListeTracker.removeAllItems();;
        for (Tracker t : ts.findDispo()) {
            ListeTracker.addItem(t);
        }
    }
     private void loadVehicule() {
         ListeVehicule.removeAllItems();
        for (Vehicule v : vs.findDispo()) {
            ListeVehicule.addItem(v);
        }
    }
      private void loadVehiculeTracker() {
                  model.setRowCount(0);

        for ( VehiculeTracker v : vts.findAll()) {
           model.addRow(new Object[]{
               v.getId(),
               v.getDateDebut(),
               v.getDateFin(),
               v.getTracker(),
               v.getVehicule()
           });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Groupe = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        ListeVehicule = new javax.swing.JComboBox();
        ListeTracker = new javax.swing.JComboBox();
        DateDebut = new com.toedter.calendar.JDateChooser();
        DateFin = new com.toedter.calendar.JDateChooser();
        RadioAffecter = new javax.swing.JRadioButton();
        RadioDesaffecter = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeVehiculeTracker = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Affecter Tracker ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Date debut :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Vehicule :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Date fin :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tracker :");

        btnAjouter.setText("Valider");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        ListeVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeVehiculeActionPerformed(evt);
            }
        });

        RadioAffecter.setBackground(new java.awt.Color(0, 204, 204));
        RadioAffecter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RadioAffecter.setText("Affecter");
        RadioAffecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioAffecterActionPerformed(evt);
            }
        });

        RadioDesaffecter.setBackground(new java.awt.Color(0, 204, 204));
        RadioDesaffecter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RadioDesaffecter.setText("Desaffecter");
        RadioDesaffecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioDesaffecterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(38, 38, 38)
                                .addComponent(ListeVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ListeTracker, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioDesaffecter, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioAffecter, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(DateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(RadioDesaffecter))
                                .addComponent(DateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel6))
                                .addComponent(ListeVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ListeTracker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RadioAffecter)
                        .addGap(41, 41, 41)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste Des"));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        listeVehiculeTracker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date debut", "Date fin ", "Tracker", "Vehicule"
            }
        ));
        listeVehiculeTracker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeVehiculeTrackerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeVehiculeTracker);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListeVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeVehiculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListeVehiculeActionPerformed

    private void listeVehiculeTrackerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeVehiculeTrackerMouseClicked
        
        id = Integer.parseInt( model.getValueAt(listeVehiculeTracker.getSelectedRow(),0).toString());
        DateDebut.setDate((Date) model.getValueAt(listeVehiculeTracker.getSelectedRow(), 1));
        DateFin.setDate((Date) model.getValueAt(listeVehiculeTracker.getSelectedRow(), 2));
        ListeTracker.getModel().setSelectedItem((Tracker)model.getValueAt(listeVehiculeTracker.getSelectedRow(), 3));
        ListeVehicule.getModel().setSelectedItem((Vehicule)model.getValueAt(listeVehiculeTracker.getSelectedRow(), 4));
        // TODO add your handling code here:
    }//GEN-LAST:event_listeVehiculeTrackerMouseClicked

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
        if(id!=0){
                     int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment Désaffecter ce Tracker");

        if (reponse == 0 ) {
            if (vts.delete(vts.findById(id))) {
                JOptionPane.showMessageDialog(this, "Tracker Désaffecté ");
                loadVehiculeTracker();
            id=0;
            } 
        }}
    }//GEN-LAST:event_btnSupprimerActionPerformed

    public boolean TrackerAffected(Tracker t){
        for (VehiculeTracker v : vts.findAll()){
            if(v.getTracker().getId()==t.getId()){
                if(v.getDateFin()==null){
                    return true;
                }
            }
        }
        return false;
    }
      public boolean VehiculeHasTracker(Vehicule t){
        for (VehiculeTracker v : vts.findAll()){
            if(v.getVehicule().getId()==t.getId()){
                if(v.getDateFin()==null){
                    return true;
                }
            }
        }
        return false;
    }
    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
        
        Date dateDebut = null;
        Date datefin = null;
        Tracker tracker = (Tracker) ListeTracker.getSelectedItem();
        Vehicule vehicule  =  (Vehicule) ListeVehicule.getSelectedItem();
        
       if (RadioAffecter.isSelected()){
           dateDebut = DateDebut.getDate();
           if(dateDebut!=null){
           if(!VehiculeHasTracker(vehicule)){
               if(!TrackerAffected(tracker)){
                  if( vts.create(new VehiculeTracker(dateDebut, datefin, vehicule, tracker))){
                      JOptionPane.showMessageDialog(this, "Tracker a bien affecté . " );
                  }else{
                      JOptionPane.showMessageDialog(this, "Erreur !!! " );

                  }
               }else{
                   JOptionPane.showMessageDialog(this, "Ce tracker deja affecter a une vehicule  !!!  ");
               }
           }else{
               JOptionPane.showMessageDialog(this, "Cette vehicule a deja un tracker affecter  !!! ");
           }
           }else{
               JOptionPane.showMessageDialog(this, "Remplire la date de Debut !!  ");

           } 
       }else if(RadioDesaffecter.isSelected()){
           if(id!=0){
               if(vts.findById(id).getDateFin()==null){
                   datefin = DateFin.getDate();
                   dateDebut =vts.findById(id).getDateDebut();
                   if (vts.testDates(datefin, dateDebut)){
                       
                       VehiculeTracker t = vts.findById(id);
                       t.setDateFin(datefin);
                       if (vts.update(t))
                            JOptionPane.showMessageDialog(this, "Bien Desaffecter . " );
                       else
                           JOptionPane.showMessageDialog(this, "Erreur   !! " );
                   }else{
                       JOptionPane.showMessageDialog(this, "la date fin est superieur a la date de debut   !!! " );

                   }
               }else{
                   JOptionPane.showMessageDialog(this, "Deja desaffecter  !! " );
               }
           }else{
                JOptionPane.showMessageDialog(this, "Selectionne une ligne  !! " );

           }
         
       }
       loadVehiculeTracker();
       loadVehicule();
       loadTrackers();

    }//GEN-LAST:event_btnAjouterActionPerformed

    private void RadioAffecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioAffecterActionPerformed
        // TODO add your handling code here:
        if (RadioAffecter.isSelected()){
            DateFin.setEnabled(false);
            DateDebut.setEnabled(true);
        }
    }//GEN-LAST:event_RadioAffecterActionPerformed

    private void RadioDesaffecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioDesaffecterActionPerformed
        // TODO add your handling code here:
            if (RadioDesaffecter.isSelected()){
            DateFin.setEnabled(true);
            DateDebut.setEnabled(false);
        }
        
    }//GEN-LAST:event_RadioDesaffecterActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jScrollPane1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateDebut;
    private com.toedter.calendar.JDateChooser DateFin;
    private javax.swing.ButtonGroup Groupe;
    private javax.swing.JComboBox ListeTracker;
    private javax.swing.JComboBox ListeVehicule;
    private javax.swing.JRadioButton RadioAffecter;
    private javax.swing.JRadioButton RadioDesaffecter;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listeVehiculeTracker;
    // End of variables declaration//GEN-END:variables
}
